package com.joffrey.iracingapp.model.iracing.defines;

public enum TrkSurf {
    irsdk_SurfaceNotInWorld,
    irsdk_UndefinedMaterial,

    irsdk_Asphalt1Material,
    irsdk_Asphalt2Material,
    irsdk_Asphalt3Material,
    irsdk_Asphalt4Material,
    irsdk_Concrete1Material,
    irsdk_Concrete2Material,
    irsdk_RacingDirt1Material,
    irsdk_RacingDirt2Material,
    irsdk_Paint1Material,
    irsdk_Paint2Material,
    irsdk_Rumble1Material,
    irsdk_Rumble2Material,
    irsdk_Rumble3Material,
    irsdk_Rumble4Material,

    irsdk_Grass1Material,
    irsdk_Grass2Material,
    irsdk_Grass3Material,
    irsdk_Grass4Material,
    irsdk_Dirt1Material,
    irsdk_Dirt2Material,
    irsdk_Dirt3Material,
    irsdk_Dirt4Material,
    irsdk_SandMaterial,
    irsdk_Gravel1Material,
    irsdk_Gravel2Material,
    irsdk_GrasscreteMaterial,
    irsdk_AstroturfMaterial,
}
